# Generated by Django 4.1.2 on 2023-04-12 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
